# Generated by Django 5.1.6 on 2025-03-21 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gallery", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "slug",
                    models.SlugField(max_length=255, unique=True, verbose_name="Url"),
                ),
            ],
            options={
                "verbose_name": "Категория(ю)",
                "verbose_name_plural": "Категории",
                "ordering": ["title"],
            },
        ),
        migrations.AddField(
            model_name="gallery",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="gallery.category",
            ),
        ),
    ]
