# Generated by Django 5.1.6 on 2025-03-19 03:15

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="full_description",
            field=django_ckeditor_5.fields.CKEditor5Field(
                verbose_name="Полное описание"
            ),
        ),
    ]
